//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int Id { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string VIN { get; set; }
        public string Mileage { get; set; }
        public int Horsepower { get; set; }
        public string RegisterSign { get; set; }
        public int OwnerId { get; set; }
        public string Photo { get; set; }
        public string correctPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(Photo) || String.IsNullOrWhiteSpace(Photo))
                {
                    return "/Resources/emptycar.png";
                }
                else
                {
                    return $"/Resources/{Photo}";
                }
            }
        }

        public virtual Owner Owner { get; set; }
    }
}
